### ISSUE TITLE
Error after importing it as a module in android studio

### ISSUE THREAD

**Issue by ankushgambhir** [OrangeGangsters/CircularBarPager#1]
Error:Artifact 'library.aar (com.viewpagerindicator:library:2.4.1)' not found.
Searched in the following locations:
    https://jcenter.bintray.com/com/viewpagerindicator/library/2.4.1/library-2.4.1.aar

**Comment by olivierg13** [comment]
Hello @ankushgambhir 

Have you tried with:
 //CircularBarPager
   compile 'com.github.orangegangsters:library:2.4.1@aar'

(which is indicated in the README)

**Comment by ankushgambhir** [comment]
Yes I added it to my app build.gradle file. 
The error I received is as soon as I imported Library as a MODULE (Existing Android Project)
Should I import it like (Import .jar or .AAR package)?

**Comment by olivierg13** [comment]
@ankushgambhir 

You mean that it doesn't work in another module project? Or it doesn't work at all?

Normally you should import it as an aar, since it includes parts of views, that's better.

There is a dependency towards viewpagerindicator in the project, but it should be compiled within the library. Could you try adding this line in your build.gradle (in addition to this library)?

compile 'com.viewpagerindicator:library:2.4.1@aar'

Cheers,

Olivier

**Comment by ktomek** [comment]
Hi @ankushgambhir 

You have to add in your main build.gradle

allprojects {
    repositories {
        maven { url 'http://dl.bintray.com/populov/maven/' }
        jcenter()
    }
}

Cheers 
Tomasz

**Comment by olivierg13** [comment]
Hello @ktomek @ankushgambhir 

Good call @ktomek 
I totally forgot about the Square dependency for CirclePageIndicator.
I added the explanation about how to add the repo in the README, hopefully the problem should not occur again for other people.

Cheers,

Olivier

**Comment by slidenerd** [comment]
please edit your README file, this is what worked for me compile 'com.viewpagerindicator:library:2.4.1@aar'
